name: home-network
version: "3.8"

services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run --token $CF_TOKEN

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ./torrent/media-service/jelly-config:/config
      - ./torrent/media-service/movies:/data/movies
      - ./torrent/media-service/tv:/data/tv
    ports:
      - 8096:8096

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: $MINIO_USER
      MINIO_SECRET_KEY: $MINIO_PASSWORD
    volumes:
      - ./s3:/data
    command: server /data --console-address ":9001"

  nginx-proxy-manager:
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx:/data
      - ./letsencrypt:/etc/letsencrypt

  # db-evergreen-prod:
  #   image: postgres:15
  #   ports:
  #     - 6543:5432
  #   environment:
  #     - POSTGRES_USER=$POSTGRES_USER
  #     - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  #     - POSTGRES_DB=$POSTGRES_DB
  #   volumes:
  #     - ./postgres/evergreen/prod:/var/lib/postgresql/data

  # db-evergreen-staging:
  #   image: postgres:15
  #   ports:
  #     - 6544:5432
  #   environment:
  #     - POSTGRES_USER=$POSTGRES_USER
  #     - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  #     - POSTGRES_DB=$POSTGRES_DB
  #   volumes:
  #     - ./postgres/evergreen/staging:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
  #     PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 6545:80
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./torrent/config:/config
      - ./torrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

