volumes:
  alert_service_postgres:
  alert_service_redis:

services:
  alert_postgres_prod:
    container_name: alert_postgres_prod
    image: postgres:16
    volumes:
      - alert_service_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  alert_redis_prod:
    container_name: alert_redis_prod
    image: redis:6
    command: ["/bin/sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    volumes:
      - alert_service_redis:/data
    ports:
      - "6379:6379"
    env_file:
      - ./.env
