services: 
  vaultwarden:
    image: vaultwarden/server:latest
    volumes: 
      - ./vaultwarden:/data
    ports: 
      - 8080:80
    restart: unless-stopped
    environment:
     - WEBSOCKET_ENABLED=true

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path /var/www/certbot -d vault.moray-banana.ts.net --email fcsie55@gmail.com --agree-tos --no-eff-email