services: 
  vaultwarden:
    image: vaultwarden/server:latest
    volumes: 
      - ./vaultwarden:/data
    ports: 
      - 8080:80
    restart: unless-stopped
    environment:
     - WEBSOCKET_ENABLED=true
    command: ['tailscale', 'serve', "http://127.0.0.1:8080"]
