services: 
  vaultwarden:
    image: vaultwarden/server:latest
    volumes: 
      - vaultwarden:/data
    ports: 
      - 8080:80
    restart: unless-stopped
    user: 3000:3000
    environment:
     - WEBSOCKET_ENABLED=true


volumes:
  vaultwarden:
    driver_opts:
      type: nfs
      o: "addr=truenas,nolock,soft,nfsvers=4"
      device: ":/mnt/nas/kluster/vaultwarden"