services: 
  vaultwarden:
    image: vaultwarden/server:latest
    volumes: 
      - vaultwarden:/data
    ports: 
      - 8080:80
    restart: unless-stopped
    environment:
     - WEBSOCKET_ENABLED=true


volumes:
  vaultwarden:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.19,rw,vers=4.1
      device: ":/mnt/nas/kluster/vaultwarden"