services: 
  vaultwarden:
    image: vaultwarden/server:latest
    volumes: 
      - ./vaultwarden:/data
    ports: 
      - 8080:80
    restart: always
    environment:
     - WEBSOCKET_ENABLED=true
