name: home-network
version: "3.8"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - 433:433
      - 8053:80
    environment:
      TZ: 'Asia/Singapore'
      WEBPASSWORD: $PIHOLE_PASSWORD
    dns:
      - 127.0.0.1
      - 8.8.8.8
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: always

